import { ImageSourcePropType } from 'react-native';

export const apiKey = process.env.EXPO_PUBLIC_API_KEY;

export const weatherImages: Record<string, ImageSourcePropType> = {
  '0': require('../assets/images/emptyStar.png'),

  '1000': require('../assets/images/sun.png'),
  '1100': require('../assets/images/sun.png'),
  '1101': require('../assets/images/partlycloudy.png'),
  '1102': require('../assets/images/partlycloudy.png'),
  '1001': require('../assets/images/cloud.png'),
  '2000': require('../assets/images/mist.png'),
  '2100': require('../assets/images/mist.png'),
  '4000': require('../assets/images/mist.png'),
  '4001': require('../assets/images/moderaterain.png'),
  '4200': require('../assets/images/moderaterain.png'),
  '4201': require('../assets/images/heavyrain.png'),

  '5000': require('../assets/images/emptyStar.png'),
  '5001': require('../assets/images/emptyStar.png'),
  '5100': require('../assets/images/emptyStar.png'),
  '5101': require('../assets/images/emptyStar.png'),
  '6000': require('../assets/images/emptyStar.png'),
  '6001': require('../assets/images/emptyStar.png'),
  '6200': require('../assets/images/emptyStar.png'),
  '6201': require('../assets/images/emptyStar.png'),
  '7000': require('../assets/images/emptyStar.png'),
  '7101': require('../assets/images/emptyStar.png'),
  '7102': require('../assets/images/emptyStar.png'),
  '8000': require('../assets/images/emptyStar.png'),

  // '5000': 'Snow',
  // '5001': 'Flurries',
  // '5100': 'Light Snow',
  // '5101': 'Heavy Snow',
  // '6000': 'Freezing Drizzle',
  // '6001': 'Freezing Rain',
  // '6200': 'Light Freezing Rain',
  // '6201': 'Heavy Freezing Rain',
  // '7000': 'Ice Pellets',
  // '7101': 'Heavy Ice Pellets',
  // '7102': 'Light Ice Pellets',
  // '8000': 'Thunderstorm',
};

export const weatherCodes: Record<string, string> = {
  '0': 'Unknown',
  '1000': 'Clear, Sunny',
  '1100': 'Mostly Clear',
  '1101': 'Partly Cloudy',
  '1102': 'Mostly Cloudy',
  '1001': 'Cloudy',
  '2000': 'Fog',
  '2100': 'Light Fog',
  '4000': 'Drizzle',
  '4001': 'Rain',
  '4200': 'Light Rain',
  '4201': 'Heavy Rain',
  '5000': 'Snow',
  '5001': 'Flurries',
  '5100': 'Light Snow',
  '5101': 'Heavy Snow',
  '6000': 'Freezing Drizzle',
  '6001': 'Freezing Rain',
  '6200': 'Light Freezing Rain',
  '6201': 'Heavy Freezing Rain',
  '7000': 'Ice Pellets',
  '7101': 'Heavy Ice Pellets',
  '7102': 'Light Ice Pellets',
  '8000': 'Thunderstorm',
};
